/**
 * Context-window compaction for OpenAI bot conversations.
 *
 * Strategy: keep system + summarize middle + keep last K rounds.
 *
 * Triggered when last_token_count > 80% of model_context_window.
 *
 *   before:  [system, m1, m2, m3, ..., mN]   (90k of 100k tokens)
 *
 *   after:   [system, {assistant: "Summary of earlier work: ..."}, m_(N-K+1), ..., mN]
 *
 * The summary is generated by a one-shot call to the same provider.
 */

import type { OpenAIMessage } from './types.js';
import { log, warn } from './logger.js';

// Model → context window mapping. Tokens, not characters.
// Add new providers/models as we use them. Default 32k for unknown models.
const MODEL_CONTEXT_WINDOWS: Record<string, number> = {
  // DeepSeek
  'deepseek-chat': 64000,
  'deepseek-reasoner': 64000,
  // Moonshot / Kimi
  'moonshot-v1-8k': 8000,
  'moonshot-v1-32k': 32000,
  'moonshot-v1-128k': 128000,
  // OpenAI
  'gpt-4o': 128000,
  'gpt-4o-mini': 128000,
  'gpt-4-turbo': 128000,
  // Groq
  'llama-3.3-70b-versatile': 128000,
  'llama-3.1-70b-versatile': 32000,
};

const DEFAULT_CONTEXT_WINDOW = 32000;
const COMPACTION_THRESHOLD = 0.8; // 80% of window
const KEEP_LAST_MESSAGES = 12; // ~6 user/assistant rounds verbatim

export function getContextWindow(model: string): number {
  return MODEL_CONTEXT_WINDOWS[model] ?? DEFAULT_CONTEXT_WINDOW;
}

export function shouldCompact(model: string, lastTokenCount: number): boolean {
  const window = getContextWindow(model);
  return lastTokenCount > window * COMPACTION_THRESHOLD;
}

/**
 * Run the compaction. Calls the provider once to summarize the middle, then
 * returns the new (shorter) message history.
 *
 * If summarization fails, returns the original history unchanged and logs a
 * warning — the next wake will try again.
 */
export async function compact(
  history: OpenAIMessage[],
  baseUrl: string,
  apiKey: string,
  model: string,
): Promise<OpenAIMessage[]> {
  if (history.length === 0) return history;

  // Find the system message (always at index 0 if present)
  const systemMsg = history[0]?.role === 'system' ? history[0] : null;
  const startIdx = systemMsg ? 1 : 0;

  // Identify the tail (last K messages) and the middle (everything between)
  if (history.length - startIdx <= KEEP_LAST_MESSAGES) {
    // Nothing to compact — already shorter than the keep-tail size
    return history;
  }

  const tail = history.slice(history.length - KEEP_LAST_MESSAGES);
  const middle = history.slice(startIdx, history.length - KEEP_LAST_MESSAGES);

  log(
    'compactor',
    `Compacting ${history.length} msgs → keep system + summarize ${middle.length} middle + keep last ${tail.length}`,
  );

  // Serialize the middle for the summarization prompt. Truncate huge tool
  // results so the summarization call itself doesn't blow the window.
  const serialized = middle
    .map((m) => {
      if (m.role === 'system') return null; // shouldn't happen, but skip
      if (m.role === 'user') return `[USER]\n${m.content}`;
      if (m.role === 'assistant') {
        if (m.tool_calls && m.tool_calls.length > 0) {
          const calls = m.tool_calls
            .map((c) => `${c.function.name}(${c.function.arguments.slice(0, 200)})`)
            .join(', ');
          return `[ASSISTANT tool_calls=${calls}]${m.content ? '\n' + m.content : ''}`;
        }
        return `[ASSISTANT]\n${m.content ?? ''}`;
      }
      if (m.role === 'tool') {
        const trimmed = m.content.length > 500 ? m.content.slice(0, 500) + '...[truncated]' : m.content;
        return `[TOOL ${m.tool_call_id.slice(0, 8)}]\n${trimmed}`;
      }
      return null;
    })
    .filter(Boolean)
    .join('\n\n');

  const summarizationPrompt =
    'You are summarizing your own past activity for context compression. ' +
    'Below are messages from your prior work session, in order. ' +
    'Produce a concise summary (under 1500 characters) of: what tasks you handled, ' +
    'what decisions you made, what comments you posted, what is still in flight. ' +
    'Be specific about task IDs, agent names, and statuses. No fluff, no greetings.\n\n' +
    serialized;

  let summary: string;
  try {
    const res = await fetch(`${baseUrl.replace(/\/$/, '')}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: summarizationPrompt }],
        stream: false,
        max_tokens: 800,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      warn('compactor', `Summarization failed: HTTP ${res.status}: ${body.slice(0, 200)}`);
      return history;
    }
    const data = (await res.json()) as {
      choices?: { message?: { content?: string } }[];
    };
    summary = data.choices?.[0]?.message?.content ?? '';
    if (!summary.trim()) {
      warn('compactor', 'Summarization returned empty content');
      return history;
    }
  } catch (err) {
    warn(
      'compactor',
      `Summarization error: ${err instanceof Error ? err.message : String(err)}`,
    );
    return history;
  }

  // Build the new history: [system?, summary as assistant, ...tail]
  const summaryMsg: OpenAIMessage = {
    role: 'assistant',
    content: `[SUMMARY OF EARLIER WORK]\n${summary.trim()}`,
  };

  const compacted: OpenAIMessage[] = [];
  if (systemMsg) compacted.push(systemMsg);
  compacted.push(summaryMsg);
  compacted.push(...tail);

  log('compactor', `Compacted: ${history.length} → ${compacted.length} messages`);
  return compacted;
}
